### PR TITLE
Update install-single-host-dgw.sh

### PR DESCRIPTION
**Pull request by zalsader**
Add branch choice for daos and ceph
Add javapackages-tools
Use gcc11

### CODE REVIEW

**Comment by zalsader** [comment]
Tested on a fresh rocky instance, works well.

**Comment by trshaffer** [comment]
Should the script install GCC 11? Just had it fail and see that this is mentioned in the steps of the main guide but not the script

**Comment by zalsader** [comment]
> Should the script install GCC 11? Just had it fail and see that this is mentioned in the steps of the main guide but not the script

Updated so it does that

**Review by trshaffer — APPROVED** [review]
Works for me!

**Pull request merged**
